version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zokeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-produto
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  #Cria o topico que precisamos
  init-kafka:
    image: wurstmeister/kafka
    depends_on:
      - kafka
    entrypoint: ['bin/sh', '-c']
    command: |
      "
        cd opt/kafka_2.13-2.8.1/bin
        kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 3 --partitions 3 --topic produto-nome
      "